### ISSUE TITLE
点赞👍

### ISSUE THREAD

**Issue by dirkhe1051931999** [fmfe/vue-class-setup#1]
【其实不太想讨论这个问题，喜欢的自然会喜欢，不喜欢的自然会不喜欢，世上本无路，走的人多了，就有了路。】----https://www.v2ex.com/t/882270

**Comment by dirkhe1051931999** [comment]
我也喜欢用class，感觉vue3的setup reactive 写起来太啰嗦了，public private 写起来多爽，但是还想用vue3的特性，你的工具满足了我！

**Comment by lzxb** [comment]
哈哈，我喜欢 class 最重要的原因是在TS里面能够更方便重构，代码跳转一步到位，组合函数可能要跳转或者选择多个，因为在 return的时候会断掉

**Comment by dirkhe1051931999** [comment]
有没有使用vue-class-setup的demo

**Comment by dirkhe1051931999** [comment]
还有
如何导入组件?

**Comment by lzxb** [comment]
可以看看这个：https://github.com/lzxb/vue-demo

**Comment by lzxb** [comment]
怎么导入组件，平时怎么写就怎么导入，这个不是这个库来决定的。

**Comment by dirkhe1051931999** [comment]
![image](https://user-images.githubusercontent.com/22389976/200220229-f475d9ef-a34f-4791-95c0-044e2fc5472b.png)
我用的是vue2.6+vue-property-decorator 需要注册组件
如果我升级到2.7 那么引入的组件无需再注册？对吧

**Comment by lzxb** [comment]
这个是在setup中引入的组件，不需要注册。你需要看下官方文档:
https://cn.vuejs.org/api/sfc-script-setup.html#basic-syntax

**Comment by lzxb** [comment]
我现在的做法都是在新开发的组件上使用setup，老的组件不动。
