### ISSUE TITLE
初次vue3使用记录

### ISSUE THREAD

**Issue by RyioGo** [fmfe/vue-class-setup#3]
1.组件注册ref需要使用方法回调
2.组件向外暴露的方法进行修改属性值无法响应页面

**Comment by RyioGo** [comment]
![WX20230220-171049@2x](https://user-images.githubusercontent.com/104488170/220062210-ea806449-e654-4273-aead-71f5dd508dde.png)
![WX20230220-171116@2x](https://user-images.githubusercontent.com/104488170/220062270-de51f7dc-4744-49c5-8237-c7a8fbb156cc.png)
![Uploading WX20230220-171138@2x.png…]()

**Comment by lzxb** [comment]
组件向外暴露，可以使用 get set 访问器来处理

```ts
defineExpose({
    get age() {},
    set age () {}
});
```

**Comment by lzxb** [comment]
1.组件注册ref需要使用方法回调
这个我不是很理解

**Comment by lzxb** [comment]
能上一个更具体的代码吗

**Comment by RyioGo** [comment]
非常感谢作者的回复😊，我的问题来自以下两段代码。

// 回调注册ref
```
 setMenuRef = null
<SetMenu :ref="(el) => (setMenuRef = el)" />
```

// v3 
```
const setMenuRef = ref(null)
<SetMenu ref="setMenuRef" />
```

对比以上两种方法注册ref，是不是在setup中有其他处理方案求教，多谢作者了。

**Comment by lzxb** [comment]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/8424643/220228656-6614443c-3f13-4e04-a980-556a925e0ae6.png">

将你的ref类型，设置为导出的 Expose 类型就可以了。
